### ISSUE TITLE
Task review, recommendations

### ISSUE THREAD

**Issue by KHajili98** [NaghiAliyev/PragmatechCsharpProject#1]
Tasklarda ciddi problem yoxdur. Tasklari kecdiklerinizin esasinda yaz ki sade sheylerle praktikan artsin, ireli movzularda yazmaginda problem yoxdur, amma gelen derslerde bunlari kecesen ve netice etibari ile calish kecdiklerinin tetbiqine fokuslan. Calish her taska ayri projectde yaz, indiden folder structure prinsipi formalashsin. Sabah bundan boyuk tasklar ishleyende cetinlik cekmeyesen. Hemcinin her taski eledikce gite elave et. Commit message-lari ingilisce yaz ki, verdish halina kecsin.

**Comment by NaghiAliyev** [comment]
Hər taskı ayrı projectdə yaz deyəndə nəyi nəzərdə tutursan? Mən bu həftə üçün bir project daxilində methodlarla yazmışdım amma əsasən fərqli projectlərdə yazacam amma qaranlıq qalan o oldu ki mən bir solution daxilində hər həftə üçün bir projectdən istifadə etməyi planlaşdırıram bu problem yaratmaz?

**Comment by KHajili98** [comment]
problem yaratmagi deyil mesele. Esas demek istediyim odur ki, her hefte ayri ve her task ayri solutionda olsun. Yeni tasklar birbirine qarishmasin.

**Comment by NaghiAliyev** [comment]
Ümid edirəm ki, qismən dediyinə əməl etdim amma indiki tapşırıqlar üçün fayl strukturu biraz qarışıq oldu. Amma fikrimcə, bu dəyişikliklər gələcək həftələr üçün işləri asanlaşdırmış olacaq.
