### ISSUE TITLE
week 4- task 4

### ISSUE THREAD

**Issue by KHajili98** [NaghiAliyev/PragmatechCsharpProject#3]
![image](https://user-images.githubusercontent.com/68163357/124356441-0c1d1580-dc27-11eb-8875-237b0f01c818.png)

` Console.Write($"{i}. uzvun adini daxil edin: ");` burada i+1 olmalidir. Ciddi xeta deyil, yeqin gozunden qacibdir.

**Comment by NaghiAliyev** [comment]
Elədir yadımdan çıxıb, fikirləşirdim ki düzəldib push etmişəm.
